# Generated by Django 4.2.16 on 2026-03-26 17:31

from django.db import migrations
from django.utils.text import slugify


CITIES = [
    'Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya',
    'Adana', 'Konya', 'Gaziantep', 'Mersin', 'Diyarbakir',
    'Kayseri', 'Eskisehir', 'Samsun', 'Trabzon', 'Denizli',
    'Malatya', 'Erzurum', 'Sanliurfa', 'Van', 'Kocaeli',
]


def seed_hubs(apps, schema_editor):
    Hub = apps.get_model('accounts', 'Hub')
    for city in CITIES:
        Hub.objects.get_or_create(name=city, defaults={'slug': slugify(city)})


def unseed_hubs(apps, schema_editor):
    Hub = apps.get_model('accounts', 'Hub')
    Hub.objects.filter(slug__in=[slugify(c) for c in CITIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_hub_model_and_user_hub_fcm'),
    ]

    operations = [
        migrations.RunPython(seed_hubs, unseed_hubs),
    ]
