# Generated by Django 4.2.16 on 2026-04-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_profile_resource_expertise_fields'),
        ('accounts', '0003_seed_hubs'),
    ]

    operations = [
    ]
