# Generated by Django 4.2.16 on 2026-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260403_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisefield',
            name='certification_document_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
