# Generated by Django 4.2.16 on 2026-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_expertisecategory_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
