# Generated by Django 4.2.16 on 2026-05-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staff_roles_and_audit'),
        ('accounts', '0009_alter_expertisecategory_id'),
    ]

    operations = [
    ]
