# Generated by Django 4.2.16 on 2026-05-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260505_2000'),
        ('accounts', '0010_usersettings'),
    ]

    operations = [
    ]
