# Generated by Django 4.2.16 on 2026-05-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_accounts_parallel_heads'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffauditlog',
            new_name='accounts_st_target__b7f377_idx',
            old_name='staff_audit_target_idx',
        ),
        migrations.RenameIndex(
            model_name='staffauditlog',
            new_name='accounts_st_action_c22bb3_idx',
            old_name='staff_audit_action_ts_idx',
        ),
    ]
