# Generated by Django 4.2.16 on 2026-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_accounts_parallel_heads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardevent',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='staffauditlog',
            new_name='accounts_st_target__b7f377_idx',
            old_name='staff_audit_target_idx',
        ),
        migrations.RenameIndex(
            model_name='staffauditlog',
            new_name='accounts_st_action_c22bb3_idx',
            old_name='staff_audit_action_ts_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contribution_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trust_points',
        ),
        migrations.AlterField(
            model_name='profile',
            name='completed_help_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RewardEvent',
        ),
    ]
