# Generated by Django 6.0.5 on 2026-05-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_rewardevent_user_and_more'),
    ]

    operations = [
    ]
