# Generated by Django 6.0.5 on 2026-05-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_0010_merge_20260505_2000_0010_usersettings'),
        ('accounts', '0015_profile_contribution_count_profile_trust_points_and_more'),
    ]

    operations = [
    ]
