# Generated by Django 4.2.16 on 2026-04-29 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshOfflineMessage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('author_device_id', models.CharField(max_length=64)),
                ('author_display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.TextField()),
                ('created_at', models.BigIntegerField()),
                ('received_at', models.BigIntegerField()),
                ('ttl_hours', models.IntegerField(default=72)),
                ('hop_count', models.IntegerField(default=0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('loc_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('loc_captured_at', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('post_type', models.CharField(blank=True, max_length=16, null=True)),
                ('parent_post_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_mesh_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent_post_id', '-created_at'], name='mesh_meshof_parent__33950d_idx')],
            },
        ),
    ]
