# Generated by Django 4.2.16 on 2026-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
