# Generated by Django 4.2.16 on 2026-05-09 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help_requests', '0003_add_other_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_help_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
