# Generated by Django 6.0.5 on 2026-05-09 19:19

from django.db import migrations

def create_default_badges(apps, schema_editor):
    # We use apps.get_model instead of importing directly in migrations!
    Badge = apps.get_model('badges', 'Badge')
    
    # Define your default badges here
    default_badges = [
        {
            "name": "Commenter",
            "description": "Awarded for commenting.",
            "icon": "🗣️",
            "criteria_type": "COMMENTS", # Adjust to whatever your exact string is
            "max_level": 5,
            "milestones": [1, 5, 10, 20, 100]
        },
        {
            "name": "Voter",
            "description": "Awarded for voting on posts.",
            "icon": "⚖️",
            "criteria_type": "VOTES", # Adjust if you added this criteria
            "max_level": 6,
            "milestones": [1, 5, 10, 50, 100, 200]
        },
        {
            "name": "Forum Active",
            "description": "Gained by creating Forum Posts",
            "icon": "📣",
            "criteria_type": "POSTS", # Adjust if you added this criteria
            "max_level": 7,
            "milestones": [1, 3, 5, 10, 20, 35, 50]
        },
        {
            "name": "Responder",
            "description": "Awarded for responding to Help Requests",
            "icon": "⛑️",
            "criteria_type": "HELP_RESPONSES",
            "max_level": 7,
            "milestones": [1, 2, 3, 5, 10, 20, 30]
        }
    ]

    for badge_data in default_badges:
        # get_or_create ensures we don't accidentally create duplicates
        Badge.objects.get_or_create(
            name=badge_data["name"],
            defaults=badge_data
        )

def reverse_badges(apps, schema_editor):
    # Optional: Logic to delete them if we ever un-migrate
    Badge = apps.get_model('badges', 'Badge')
    Badge.objects.filter(name__in=["Conversationalist", "Voter", "Forum Active", "Responder"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        # This will automatically be filled with your previous migration file name
        ('badges', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_default_badges, reverse_badges),
    ]