# Generated by Django 4.2.16 on 2026-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_seed_default_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('POSTS', 'Forum Posts Created'), ('COMMENTS', 'Comments Made'), ('VOTES', 'Votes Cast'), ('HELP_RESPONSES', 'Help Responses')], help_text='The exact action this badge tracks.', max_length=50, unique=True),
        ),
    ]
