# Generated by Django 4.2.16 on 2026-03-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial_forum_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='forum.post'),
        ),
    ]
