# Generated by Django 4.2.16 on 2026-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_add_reposted_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
