# Generated by Django 4.2.16 on 2026-03-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_hubs'),
        ('forum', '0003_add_repost_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('URGENT', 'Urgent'), ('GLOBAL', 'Global')], default='STANDARD', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.hub'),
        ),
    ]
